### ISSUE TITLE
可 Copy 的类型没有所有权

### ISSUE THREAD

**Issue by spike014** [yaoming00/rust-practice#1]
那么哪些类型实现了 Copy trait 呢？你可以查看给定类型的文档来确认，不过作为一个通用的规则，任何一组简单标量值的组合都可以实现 Copy，任何不需要分配内存或某种形式资源的类型都可以实现 Copy 。如下是一些 Copy 的类型：

- 所有整数类型，比如 u32。
- 布尔类型，bool，它的值是 true 和 false。
- 所有浮点数类型，比如 f64。
- 字符类型，char。
- 元组，当且仅当其包含的类型也都是 Copy 的时候。比如，(i32, i32) 实现了 Copy ，但 (i32, String) 没有。

**Comment by yaoming00** [comment]
from https://github.com/sunface/rust-course
